spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/productdb
    username: postgres
    password: postgres   # your PG password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

splunk:
  hec:
    url: http://localhost:8088
    token: 82d3b871-1db4-4da8-983a-6c08bed3f0b9
    index: main
    source-type: springboot-logs

eureka:
  client:
    enabled: false

